#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ybp.Gobile.Android.Resource", IsApplication=true)]

namespace Ybp.Gobile.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Ybp.Gobile.Android.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Ybp.Gobile.Android.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Ybp.Gobile.Android.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int gobi_blue = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int gobi_orange = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int accountLabel = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int accountText = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int button2 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int contentFrame = 2131165195;
			
			// aapt resource value: 0x7f070006
			public const int loginButton = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int loginIdLabel = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int loginProgress = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int loginidtext = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int passwordLabel = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int passwordtext = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int responseText = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int scanButton = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Search = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int zxingscanneractivitylayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int zxingscannerfragmentlayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public const int ApplicationName = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int account = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int login = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int loginid = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int password = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int GobiCustomTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
